/**
 * `donna init` — Interactive setup wizard
 * Guides users through API key configuration and system dependency checks
 */

import { writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { createInterface } from 'readline';
import { store } from './store.js';

/**
 * Prompt the user for input via readline
 */
function prompt(question: string, defaultValue?: string): Promise<string> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const suffix = defaultValue ? ` (${defaultValue})` : '';

  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue || '');
    });
  });
}

/**
 * Check if a system command is available
 */
async function commandExists(cmd: string): Promise<boolean> {
  const { exec } = await import('child_process');
  return new Promise((resolve) => {
    exec(`which ${cmd}`, (error) => {
      resolve(!error);
    });
  });
}

/**
 * Run the init wizard
 */
export async function runInit(): Promise<void> {
  console.log('\n🌟 \x1b[36mDonna CLI Setup\x1b[0m\n');
  console.log('This wizard will help you configure Donna.\n');

  // Check system dependencies
  console.log('📋 \x1b[90mChecking system dependencies...\x1b[0m\n');

  const hasSox = await commandExists('sox');
  const hasArecord = await commandExists('arecord');
  const hasMpv = await commandExists('mpv');

  if (!hasSox && !hasArecord) {
    console.log('⚠️  \x1b[33mNeither sox nor arecord found.\x1b[0m');
    console.log('   Voice input requires one of these. Install with:');
    console.log('   \x1b[90m• Ubuntu/Debian: sudo apt install sox alsa-utils\x1b[0m');
    console.log('   \x1b[90m• macOS: brew install sox\x1b[0m\n');
  } else {
    console.log(`✅ Audio recording: ${hasSox ? 'sox' : 'arecord'} found`);
  }

  if (!hasMpv) {
    console.log('⚠️  \x1b[33mmpv not found.\x1b[0m');
    console.log('   Audio playback may be limited. Install with:');
    console.log('   \x1b[90m• Ubuntu/Debian: sudo apt install mpv\x1b[0m');
    console.log('   \x1b[90m• macOS: brew install mpv\x1b[0m\n');
  } else {
    console.log('✅ Audio playback: mpv found');
  }

  console.log('');

  // Collect API keys
  let llmProvider = '';
  while (llmProvider !== 'openai' && llmProvider !== 'gemini') {
    llmProvider = await prompt('🧠 Provider (openai/gemini)', 'gemini');
    llmProvider = llmProvider.toLowerCase();
  }

  let openaiKey = '';
  let geminiKey = '';
  let model = '';

  if (llmProvider === 'openai') {
    openaiKey = await prompt('🔑 OpenAI API Key');
    model = await prompt('🤖 OpenAI Model', 'gpt-4o');
    if (!openaiKey.startsWith('sk-')) {
      console.log('\n⚠️  \x1b[33mOpenAI key doesn\'t look right (should start with sk-). Saving anyway.\x1b[0m');
    }
  } else {
    geminiKey = await prompt('🔑 Gemini API Key');
    model = await prompt('🤖 Gemini Model', 'gemini-2.5-flash');
  }

  const elevenLabsKey = await prompt('🔑 ElevenLabs API Key');
  const voiceId = await prompt('🎤 ElevenLabs Voice ID', '21m00Tcm4TlvDq8ikWAM');

  // Write .env file
  const envPath = resolve(process.cwd(), '.env');
  const envContent = [
    `# Donna CLI Configuration — generated by 'donna init'`,
    `LLM_PROVIDER=${llmProvider}`,
    openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '',
    geminiKey ? `GEMINI_API_KEY=${geminiKey}` : '',
    `ELEVENLABS_API_KEY=${elevenLabsKey}`,
    `ELEVENLABS_VOICE_ID=${voiceId}`,
    llmProvider === 'openai' ? `OPENAI_MODEL=${model}` : `GEMINI_MODEL=${model}`,
    '',
  ].filter(line => line !== '').join('\n');

  if (existsSync(envPath)) {
    const overwrite = await prompt('⚠️  .env already exists in current directory. Overwrite? (y/N)', 'N');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n\x1b[90mSkipping .env write. Keys saved globally.\x1b[0m');
    } else {
      writeFileSync(envPath, envContent);
      console.log('\n✅ .env file updated');
    }
  } else {
    const createEnv = await prompt('Would you like to also create a .env file here? (y/N)', 'N');
    if (createEnv.toLowerCase() === 'y') {
      writeFileSync(envPath, envContent);
      console.log('\n✅ .env file created');
    } else {
      console.log('\n✅ Keys saved globally to your profile.');
    }
  }

  // Update persistent config
  store.set('initialized', true);
  store.set('voiceId', voiceId);
  store.set('llmProvider', llmProvider as 'openai' | 'gemini');
  store.set('model', model);
  if (openaiKey) store.set('openaiKey', openaiKey);
  if (geminiKey) store.set('geminiKey', geminiKey);
  store.set('elevenLabsKey', elevenLabsKey);

  console.log('\n🚀 \x1b[36mDonna is ready!\x1b[0m');
  console.log('   Run \x1b[1mdonna\x1b[0m to start a voice session.\n');
}
